export default function AboutPage() {
  return <div>This is my about</div>;
}

animals
page.js

export const metadata = {
  title: 'Animals Page',
  description: 'Generated by create next app',
};

export default function AnimalsPage() {
  return <div>This is my animals page</div>;
}
