import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home Page | Upleveled', template: '%s | Upleveled' },
  description: 'Generated by create next app',
};
// Bu "children" applicationdaki hersey demek. Bütün dosyalar, bütün routlar vs.... ( layoutlarin genel durumu böyle)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <a href="/">Home</a>
          <a href="/about">About</a>
          <a href="/animals">Animals</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
