import Link from 'next/link';

export const metadata = {
  title: 'Products Page',
  description: 'Generated by create next app',
};

export default function ProductsPage() {
  return (
    <div>
      <h2>List of our COol Toys</h2>
      <ol>
        <li>
          <Link href="/">Product 1</Link>
        </li>
        <li>
          <Link href="/about">Product 2</Link>
        </li>
        <li>
          <Link href="/products">Product 3</Link>
        </li>
        <li>
          <Link href="/">Product 4</Link>
        </li>
      </ol>
    </div>
  );
}
