import Image from 'next/image';
import Link from 'next/link';
import { getProducts } from '../../database/products';

export const metadata = {
  title: 'Products Page',
  description: 'Generated by create next app',
};

export default function ProductsPage() {
  const products = getProducts();
  return (
    <div>
      <h1>These are my CoOl Toys:</h1>

      {products.map((product) => {
        return (
          <div key={`product-div-${product.id}`}>
            <Link href={`/products/${product.id}`}>{product.toyName}</Link>
            <Image
              src={`/images/${product.toyName}.jpg`}
              alt={product.toyName}
              width={500}
              height={400}
            />
          </div>
        );
      })}
    </div>
  );
}
